name: Build and Deploy 2

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      # - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      # - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
      - name: Build
          # npm install
        run: |
          echo ------------------
          echo INSTALADO COMPLETO
          echo ------------------
          echo ------------------
          npm run-script deploy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/web-antonio




          # name: Build and Deploy
# # on:
# #   push:
# #     branches:
# #       - main
# #       - release/*
# #     pull_request:
# #       - main
      
# #     # Allows you to run this workflow manually from the Actions tab
# #     workflow_dispatch:
    
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: Angular Deploy gh-pages Actions
#       # You may pin to the exact commit or the version.
#       # uses: AhsanAyaz/angular-deploy-gh-pages-actions@26ffbdb76b46ce3d649d046f1f7f45099654cfd7
#       uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
#       with:
#         # Github access token token used to deploy on gh_pages. You can find it on Github.
#         github_access_token: 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
#         # The directory of the angular project, in which all the commands will run
#         angular_project_dir: # optional, default is ./
#         # Build configuration for the angular app
#         build_configuration: # optional, default is production
#         # base href for the app
#         base_href: https://aunamedia.github.io/web-antonio/ # optional, default is /
#         # branch on which the angular build will be deployed
#         deploy_branch: # optional, default is gh-pages
#         # The folder in which `ng build` provides its output. This is the folder which will be deployed to the `deploy_branch`.
#         angular_dist_build_folder:  dist/web-antonio # optional, default is dist
#         # If the action should run 'ng lint'
#         run_lint: # optional
#         # Will not fail the step if anything fails
#         skip_failure: # optional

  
